export const READ_USERS = "READ_USERS";
export const READ_CURRENT_USER = "READ_CURRENT_USER";
export const WRITE_CURRENT_USER = "WRITE_CURRENT_USER";
export const CREATE_USER = "CREATE_USER";
export const WRITE_USER_AS_ADMIN = "WRITE_USER_AS_ADMIN";
export const READ_USER = "READ_USER";