import {
    READ_USERS, READ_USER,
    WRITE_USER_AS_ADMIN,
    CREATE_USER,
    CREATE_ORGANIZATION, CREATE_SERVICE, WRITE_ORGANIZATION_AS_ADMIN, WRITE_SERVICE, WRITE_ORGANIZATION
} from "./permissions"
export const rolesPermissions=new Map<String, string[]>;
rolesPermissions.set("SUPER ADMIN", [WRITE_USER_AS_ADMIN,WRITE_ORGANIZATION_AS_ADMIN,CREATE_USER,READ_USERS,READ_USER])
rolesPermissions.set("CUSTOMER", [])
rolesPermissions.set("OWNER", [CREATE_ORGANIZATION,WRITE_ORGANIZATION,CREATE_SERVICE,WRITE_SERVICE])