import {READ_USERS, READ_USER, CREATE_USER, UPDATE_USER_AS_ADMIN, UPDATE_ORGANIZATION_AS_ADMIN, UPDATE_ORGANIZATION, CREATE_ORGANIZATION, CREATE_SERVICE, CREATE_ROOM, UPDATE_ROOM, UPDATE_SERVICE} from "./permissions";
export const rolesPermissions = {
    "SUPER ADMIN": [
        UPDATE_USER_AS_ADMIN,
        UPDATE_ORGANIZATION_AS_ADMIN,
        CREATE_USER,
        READ_USERS,
        READ_USER,
        UPDATE_SERVICE
    ],
    "CUSTOMER": [],
    "OWNER": [
        CREATE_ORGANIZATION,
        UPDATE_ORGANIZATION,
        CREATE_SERVICE,
        UPDATE_SERVICE,
        CREATE_ROOM,
        UPDATE_ROOM
    ]
}